@baseUrl = http://localhost:3000

# Request 0
GET https://api.github.com/users/defunkt HTTP/1.1
User-Agent: Awesome-Octocat-App

###

# Signup
POST {{baseUrl}}/api/auth/signup  HTTP/1.1
Content-Type: application/json

{
    "username":"test2",
    "email":"test2@gmail.com",
    "password":"test2"
}

###

# Signin
POST {{baseUrl}}/api/auth/signin  HTTP/1.1
Content-Type: application/json

{
    "email":"test2@gmail.com",
    "password":"test2"
}

###
# Update User
POST {{baseUrl}}/api/user/update/654de81a5d8fa98c70d41df9  HTTP/1.1
Content-Type: application/json

{
    "username":"test2"
}

###
# Create Listing
POST {{baseUrl}}/api/listing/create  HTTP/1.1
Content-Type: application/json

{
    "name":"name",
    "description":"test2",
    "address": "test2",
    "regularPrice": 100,
    "discountPrice": 90,
    "bathrooms": 2,
    "bedrooms": 4,
    "furnished": true,
    "parking": true,
    "type":"rent",
    "offer":true,
    "imageUrls": ["image1", "image2"],
    "userRef": "654de81a5d8fa98c70d41df9"
}

###
